#!/bin/bash
echo "Pre-push hook!"
cd back || exit 1
# Run backend unit tests
echo "Running backend unit tests"

# Run backend linter
if ! command -v golangci-lint &>/dev/null; then
  echo "Linter golangci-lint not found in PATH"
  exit
else
  echo "Running Go linter"
  golangci-lint run -E gosec -E gofmt
  status=$?
  if test $status -eq 0; then
    echo "Golang lint success"
  else
    echo "Golang lint failed"
    exit 1
  fi
fi
